/*          CREACION DE TABLAS        */

CREATE TABLE TBL_ESTUDIANTE (
    ID_ETD SERIAL PRIMARY KEY,          -- Clave primaria autoincremental
    ID_RT INTEGER,                      --FK REPRESENTANTE
    ID_ESTADO INTEGER,                  --FK ESTADO
    ID_DISCD INTEGER,                   --FK DISCAPACIDAD
    ID_GENERO INTEGER,                  --FK GENERO
    ID_NV_EDU INTEGER,                  --FK NIVEL EDUCACION
    ID_NCD INTEGER,                     --FK NACIONALIDAD
    ID_NIVEL_INGLES INTEGER,            --FK NIVEL INGLES
    NOMBRE_ETD VARCHAR(100) NOT NULL,
    APELLIDO_ETD VARCHAR(100) NOT NULL,
    FECHA_NACIMIENTO_ETD DATE,
    CEDULA_ETD VARCHAR(50),
    DIRECCION_ETD VARCHAR(100),
    TELEFONO_ETD VARCHAR(50),
    CORREO_ETD VARCHAR(100),
    CONTACTO_EMERGENCIA_ETD VARCHAR(50),
    QUIEN_RETIRA_ETD VARCHAR(100)
);

CREATE TABLE TBL_PAGO (
    ID_PAGO SERIAL PRIMARY KEY, -- Clave primaria autoincremental
    ID_ETD INTEGER NOT NULL,             --FK ESTUDIANTE
    ID_PERSONA INTEGER NOT NULL,         --FK PERSONA
    ID_METODO_PAGO INTEGER NOT NULL,     --FK METODO PAGO
    FCHA_PAGO DATE NOT NULL,
    MONTO_TOTAL_PAGO NUMERIC(10,2) NOT NULL,
    MONTO_CANCELADO_PAGO NUMERIC(10,2) NOT NULL,
    RENOVACION_PAGO DATE NOT NULL
);

CREATE TABLE TBL_REPRESENTANTE (
    ID_RT SERIAL PRIMARY KEY,                   -- Clave primaria autoincremental
    ID_RELACION INTEGER NOT NULL,                --FK RELACION
    ID_GENERO INTEGER NOT NULL,                  --FK GENERO
    CEDULA_RT VARCHAR(50) NOT NULL,
    NOMBRE_RT VARCHAR(100) NOT NULL,
    APELLIDO_RT VARCHAR(100) NOT NULL,
    DIRECCION_RT VARCHAR(100) NOT NULL,
    CORREO_RT VARCHAR(100) NOT NULL,
    TELEFONO_RT VARCHAR(50) NOT NULL
);

CREATE TABLE TBL_RELACION (
    ID_RELACION SERIAL PRIMARY KEY,
    NOMBRE_RELACION VARCHAR(100) NOT NULL
);
CREATE TABLE TBL_DISCAPACIDAD (
    ID_DISCD SERIAL PRIMARY KEY,
    TIPO_DISCD VARCHAR(100) NOT NULL,
    NOMBRE_DISCD VARCHAR(100) NOT NULL
);

CREATE TABLE TBL_GENERO (
    ID_GENERO SERIAL PRIMARY KEY,
    NOMBRE_GENERO VARCHAR(100) NOT NULL
);

CREATE TABLE TBL_NIVEL_EDUCACION (
    ID_NV_EDU SERIAL PRIMARY KEY,
    TIPO_NV_EDU VARCHAR(100) NOT NULL,
    NOMBRE_NV_EDU VARCHAR(100) NOT NULL
);

CREATE TABLE TBL_NACIONALIDAD (
    ID_NCD SERIAL PRIMARY KEY,
    NOMBRE_NCD VARCHAR(100) NOT NULL,
    CODIGO_NCD VARCHAR(50) NOT NULL
);

CREATE TABLE TBL_NIVEL_INGLES (
    ID_NIVEL_INGLES SERIAL PRIMARY KEY,
    NOMBRE_NIVEL_INGLES VARCHAR(100) NOT NULL
);

CREATE TABLE TBL_ALERGIA_ESTUDIANTE (
    ID_ALERGIA_ETD SERIAL PRIMARY KEY,      -- Clave primaria autoincremental
    ID_ETD INTEGER NOT NULL,                --FK ESTUDIANTE
    ID_ALERGIA INTEGER NOT NULL              --FK ALERGIA
);

CREATE TABLE TBL_ALERGIA (
    ID_ALERGIA SERIAL PRIMARY KEY,
    NOMBRE_ALERGIA VARCHAR(100) NOT NULL,
    SEVERIDAD_ALERGIA VARCHAR(100) NOT NULL
);

CREATE TABLE TBL_ESTADO (
    ID_ESTADO SERIAL PRIMARY KEY,
    NOMBRE_ESTADO VARCHAR(100) NOT NULL
);

CREATE TABLE TBL_PERIODO (
    ID_PERIODO SERIAL PRIMARY KEY,          -- Clave primaria autoincremental
    ID_PERSONA INTEGER NOT NULL,                     --FK PERSONA
    ID_ESTADO INTEGER NOT NULL,                      --FK ESTADO
    NOMBRE_PERIODO VARCHAR(100) NOT NULL,
    FECHA_INI_PERIODO DATE NOT NULL,
    FECHA_FIN_PERIODO DATE NOT NULL,
    YEAR_ACADEMICO INTEGER NOT NULL
);

CREATE TABLE TBL_INSCRIPCION (
    ID_INSCRIPCION SERIAL PRIMARY KEY,  -- Clave primaria autoincremental
    ID_ETD INTEGER NOT NULL,                     --FK ESTUDIANTE
    ID_NIVEL INTEGER NOT NULL,                   --FK NIVEL
    ID_PERIODO INTEGER NOT NULL,                 --FK PERIODO
    ID_PERSONA INTEGER NOT NULL,                 --FK PERSONA
    FECHA_INSCRIPCION DATE NOt NULL
);

CREATE TABLE TBL_NIVEL (
    ID_NIVEL SERIAL PRIMARY KEY,        -- Clave primaria autoincremental
    NOMBRE_NIVEL VARCHAR(100) NOT NULL,
    DESCRIPCION_NIVEL VARCHAR(200),
    DURACION_NIVEL VARCHAR(50) NOT NULL
);

CREATE TABLE TBL_NOTA (
    ID_NOTA SERIAL PRIMARY KEY,     -- Clave primaria autoincremental
    ID_ETD INTEGER NOT NULL,                 --FK ESTUDIANTE
    ID_NIVEL INTEGER NOT NULL,               --FK NIVEL
    ID_PERIODO INTEGER NOT NULL,             --FK PERIODO
    ID_PERSONA INTEGER NOT NULL,             --FK PERSONA
    VALOR_NOTA VARCHAR(50) NOT NULL,
    FECHA_CREACION_NOTA DATE NOT NULL
);

CREATE TABLE TBL_PERSONA (
    ID_PERSONA SERIAL PRIMARY KEY,          -- Clave primaria autoincremental
    NOMBRE_PERSONA VARCHAR(100) NOT NULL,
    APELLIDO_PERSONA VARCHAR(100) NOT NULL,
    CEDULA_PERSONA VARCHAR(50) NOT NULL,
    CARGO_PERSONA VARCHAR(100) NOT NULL
);

CREATE TABLE TBL_METODO_PAGO (
    ID_METODO_PAGO SERIAL PRIMARY KEY,          -- Clave primaria autoincremental
    NOMBRE_METODO_PAGO VARCHAR(100) NOT NULL
);

CREATE TABLE TBL_GASTO (
    ID_GASTO SERIAL PRIMARY KEY,            -- Clave primaria autoincremental
    ID_PERSONA INTEGER NOT NULL,                    --FK PERSONA
    ID_METODO_PAGO INTEGER NOT NULL,                --FK METODO PAGO
    ID_TIPO_GASTO INTEGER,                          --FK TIPO GASTO
    NOMBRE_GASTO VARCHAR(100) NOT NULL,
    DESCRIPCION_GASTO VARCHAR(200),
    FECHA_GASTO DATE NOT NULL,
    CANTIDAD_GASTO NUMERIC(10,2) NOT NULL
);

CREATE TABLE TBL_TIPO_GASTO (
    ID_TIPO_GASTO SERIAL PRIMARY KEY,           -- Clave primaria autoincremental
    NOMBRE_TIPO_GASTO VARCHAR(100) NOT NULL
);

CREATE TABLE TBL_REGISTRO_MES (
    ID_REGISTRO_MES SERIAL PRIMARY KEY,             -- Clave primaria autoincremental
    ID_PERSONA INTEGER NOT NULL,                             --FK PERSONA
    TOTAL_REGISTRO_MES NUMERIC(10,2) NOT NULL,
    GANANCIA_REGISTRO_MES NUMERIC(10,2) NOT NULL,
    GASTOS_REGISTRO_MES NUMERIC(10,2) NOT NULL,
    FECHA_INI_REGISTRO_MES DATE NOT NULL,
    FECHA_FIN_REGISTRO_MES DATE NOT NULL
);

CREATE TABLE TBL_USUARIO (
    ID_USUARIO SERIAL PRIMARY KEY,          -- Clave primaria autoincremental
    NOMBRE_USUARIO VARCHAR(50) NOT NULL,
    PASSWORD_USUARIO VARCHAR(50) NOT NULL,
    ROL_USUARIO NUMERIC(2) NOT NULL
);


--          RELACIONES DE TABLA ESTUDIANTES(7)         --

ALTER TABLE TBL_ESTUDIANTE ADD
    FOREIGN KEY (ID_RT) REFERENCES TBL_REPRESENTANTE (ID_RT)
        ON DELETE SET NULL;
    
ALTER TABLE TBL_ESTUDIANTE ADD
    FOREIGN KEY (ID_ESTADO) REFERENCES TBL_ESTADO (ID_ESTADO)
        ON DELETE SET NULL;

ALTER TABLE TBL_ESTUDIANTE ADD
    FOREIGN KEY (ID_DISCD) REFERENCES TBL_DISCAPACIDAD (ID_DISCD)
        ON DELETE SET NULL;

ALTER TABLE TBL_ESTUDIANTE ADD
    FOREIGN KEY (ID_GENERO) REFERENCES TBL_GENERO (ID_GENERO)
        ON DELETE SET NULL;

ALTER TABLE TBL_ESTUDIANTE ADD
    FOREIGN KEY (ID_NV_EDU) REFERENCES TBL_NIVEL_EDUCACION (ID_NV_EDU)
        ON DELETE SET NULL;

ALTER TABLE TBL_ESTUDIANTE ADD
    FOREIGN KEY (ID_NCD) REFERENCES TBL_NACIONALIDAD (ID_NCD)
        ON DELETE SET NULL;

ALTER TABLE TBL_ESTUDIANTE ADD
    FOREIGN KEY (ID_NIVEL_INGLES) REFERENCES TBL_NIVEL_INGLES (ID_NIVEL_INGLES)
        ON DELETE SET NULL;

--          RELACION DE TABLA DE REPRESENTANTES(2)         --

ALTER TABLE TBL_REPRESENTANTE ADD
    FOREIGN KEY (ID_RELACION) REFERENCES TBL_RELACION (ID_RELACION)
        ON DELETE SET NULL;

ALTER TABLE TBL_REPRESENTANTE ADD
    FOREIGN KEY (ID_GENERO) REFERENCES TBL_GENERO (ID_GENERO)
        ON DELETE SET NULL;

--          RELACION DE TABLA PAGO(3)          --

ALTER TABLE TBL_PAGO ADD
    FOREIGN KEY (ID_ETD) REFERENCES TBL_ESTUDIANTE (ID_ETD)
        ON DELETE SET NULL;

ALTER TABLE TBL_PAGO ADD
    FOREIGN KEY (ID_PERSONA) REFERENCES TBL_PERSONA (ID_PERSONA)
        ON DELETE SET NULL;

ALTER TABLE TBL_PAGO ADD
    FOREIGN KEY (ID_METODO_PAGO) REFERENCES TBL_METODO_PAGO (ID_METODO_PAGO)
        ON DELETE SET NULL;

--          RELACION DE TABLA ALERGIAS ESTUDIANTE(2)           --

ALTER TABLE TBL_ALERGIA_ESTUDIANTE ADD
    FOREIGN KEY (ID_ETD) REFERENCES TBL_ESTUDIANTE (ID_ETD)
        ON DELETE SET NULL;

ALTER TABLE TBL_ALERGIA_ESTUDIANTE ADD
    FOREIGN KEY (ID_ALERGIA) REFERENCES TBL_ALERGIA (ID_ALERGIA)
        ON DELETE SET NULL;

--          RELACION DE LA TABLA PERIODO(2)            --

ALTER TABLE TBL_PERIODO ADD
    FOREIGN KEY (ID_PERSONA) REFERENCES TBL_PERSONA (ID_PERSONA)
        ON DELETE SET NULL;

ALTER TABLE TBL_PERIODO ADD
    FOREIGN KEY (ID_ESTADO) REFERENCES TBL_ESTADO (ID_ESTADO)
        ON DELETE SET NULL;

--          RELACIONDE DE LA TABLA INSCRIPCION(4)            --

ALTER TABLE TBL_INSCRIPCION ADD
    FOREIGN KEY (ID_ETD) REFERENCES TBL_ESTUDIANTE (ID_ETD)
        ON DELETE SET NULL;

ALTER TABLE TBL_INSCRIPCION ADD
    FOREIGN KEY (ID_NIVEL) REFERENCES TBL_NIVEL (ID_NIVEL)
        ON DELETE SET NULL;

ALTER TABLE TBL_INSCRIPCION ADD
    FOREIGN KEY (ID_PERIODO) REFERENCES TBL_PERIODO (ID_PERIODO)
        ON DELETE SET NULL;

ALTER TABLE TBL_INSCRIPCION ADD
    FOREIGN KEY (ID_PERSONA) REFERENCES TBL_PERSONA (ID_PERSONA)
        ON DELETE SET NULL;

--          RELACION DE LA TABLA NOTA(4)            --

ALTER TABLE TBL_NOTA ADD
    FOREIGN KEY (ID_ETD) REFERENCES TBL_ESTUDIANTE (ID_ETD)
        ON DELETE SET NULL;

ALTER TABLE TBL_NOTA ADD
    FOREIGN KEY (ID_NIVEL) REFERENCES TBL_NIVEL (ID_NIVEL)
        ON DELETE SET NULL;

ALTER TABLE TBL_NOTA ADD
    FOREIGN KEY (ID_PERIODO) REFERENCES TBL_PERIODO (ID_PERIODO)
        ON DELETE SET NULL;

ALTER TABLE TBL_NOTA ADD
    FOREIGN KEY (ID_PERSONA) REFERENCES TBL_PERSONA (ID_PERSONA)
        ON DELETE SET NULL;

--          RELACION DE LA TABLA REGISTRO MES(1)          --

ALTER TABLE TBL_REGISTRO_MES ADD
    FOREIGN KEY (ID_PERSONA) REFERENCES TBL_PERSONA (ID_PERSONA)
        ON DELETE SET NULL;

--          RELACION DE LA TABALA GASTO(3)         --

ALTER TABLE TBL_GASTO ADD
    FOREIGN KEY (ID_PERSONA) REFERENCES TBL_PERSONA (ID_PERSONA)
        ON DELETE SET NULL;

ALTER TABLE TBL_GASTO ADD
    FOREIGN KEY (ID_METODO_PAGO) REFERENCES TBL_METODO_PAGO (ID_METODO_PAGO)
        ON DELETE SET NULL;

ALTER TABLE TBL_GASTO ADD
    FOREIGN KEY (ID_TIPO_GASTO) REFERENCES TBL_TIPO_GASTO (ID_TIPO_GASTO)
        ON DELETE SET NULL;

--          OTRAS RELACIONES            --
